### ISSUE TITLE
Issue in IE 8, Firefox 3.6.12

### ISSUE THREAD

**Issue by loony** [CSS-Tricks/MovingBoxes#10]
my Issue is that in IE 8 the script on line 166
base.change( base.$el.find('.panel').index($(this).closest('.panel')) + 1, false );
IE 8 doesn't slide when i push the arrow. it gives me a script warning. In Firefox it's going but i gives me a warning in the firebug console. the warning is that the .closest() isn't a function. so i changed this to next. it's solved my problem. i use linux opensuse 11.3 64x version and win7 64x version as well. i got the newest jquery. to say is that i took the moving boxes into Drupal 6.x
any idea to solve them without changing closest to next?

**Comment by Mottie** [comment]
I can't seem to duplicate the problem/error you are describing. I tried the demo (http://chriscoyier.github.com/MovingBoxes) in IE 8.0.7600.16385 and Firefox 3.6.13 without any errors.

**Comment by loony** [comment]
I done an image for you that you see what I wona say. 
(http://www.abload.de/img/moving_box_issuev56r.png). may i hope this img should help you. when I was opening ff and start to the firebug i saw them. When I was in the IE 8 the moving box wasn't doing anything just spinning to the last img. but this is an other issue.

**Comment by Mottie** [comment]
Hmm, ok what version of MovingBoxes are you using? In the latest version, the only "closest()" function is on line 127

**Comment by loony** [comment]
i use this version
/*
- Moving Boxes v1.6.3
- by Chris Coyier
- http://css-tricks.com/moving-boxes/
  */

**Comment by Mottie** [comment]
I just downloaded v1.6.3 from here to verify it again, and line 166 doesn't have a "closest()" in it. Could you mail me the copy you have? wowmotty at gmail dot com and I'll look at it

**Comment by loony** [comment]
send your my code. may it helps. thank

**Comment by Mottie** [comment]
Ahhh, I found the problem! YAY!

Your site is using jQuery version 1.2.6 and `closest()` wasn't added until version 1.3 (http://api.jquery.com/closest/).
