### ISSUE TITLE
Anchor inside panel

### ISSUE THREAD

**Issue by cormdog** [CSS-Tricks/MovingBoxes#102]
Is it possible add an anchor link inside one of the panels that would scroll to another panel. I want to create a couple questions that would then scroll to the appropriate panel. Thanks in advance.

**Comment by Mottie** [comment]
Hi @cormdog!

You can use the [API to set the panel](https://github.com/CSS-Tricks/MovingBoxes/wiki/Usage). Here's [a demo](http://jsfiddle.net/acV4n/549/) and the code:

HTML (inside panel)

``` html
<a class="mb-link" href="#2">2</a>
```

Javascript (inside of a document ready function)

``` javascript
$('.mb-link').click(function(){
    // substring(1), removes the "#" from "#1"
    $('#slider').movingBoxes( this.hash.substring(1) );
});
```

**Comment by cormdog** [comment]
Awesome thanks
