### ISSUE TITLE
Looping with a disabled left (rewind) arrow when you get back to the first image

### ISSUE THREAD

**Issue by klgreene** [CSS-Tricks/MovingBoxes#105]
I'd like for the slider to have looping functionality while maintaining the disabled left side arrow (rewind functionality) when you get back to the first image in the slider order. How would I go about doing that? Right now when I change 

wrap: true

It enables the arrows, so you can rewind to the last image in the slider even if you haven't scrolled all the way through in order. 

Any help would be much appreciated!

**Comment by Mottie** [comment]
I think this is what you are describing ([demo](http://jsfiddle.net/Mottie/acV4n/657/)):

``` javascript
$('#slider').movingBoxes({

    // if true, the panel will "wrap" (it really rewinds/fast forwards) at the ends
    wrap: true,
    // if true, navigation links will be added
    buildNav: true,
    // function which returns the navigation text for each panel
    navFormatter: function(index, panel){ return "&#9679;" },

    // callback when MovingBoxes has completed initialization
    initialized: function(e, slider, tar){
        slider.$wrap.find('.mb-left')[ tar === 1 ? 'hide' : 'show' ]();
    },
    beforeAnimation : function(e, slider, tar) {
        slider.$wrap.find('.mb-left')[ tar === 1 ? 'hide' : 'show' ]();
    }

});​
```

**Comment by klgreene** [comment]
Yes, that is exactly it! Thank you VERY much.

**Comment by Mottie** [comment]
You're welcome :)
