### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by hpatel25** [CSS-Tricks/MovingBoxes#11]
How can I remove the #&slider1=4 that gets attached to the URL when using the movingboxes?
It doesn't happen on the css tricks demo but with the downloaded files I get it.

http://css-tricks.com/examples/MovingBoxes/

thanks

**Comment by Mottie** [comment]
Hi hpatel25!

If you set the option "hashTags" to false, it turns off the URL hash tags.

**Comment by hpatel25** [comment]
thanks!!
