### ISSUE TITLE
moving box slider stop script -script slow problem

### ISSUE THREAD

**Issue by king40** [CSS-Tricks/MovingBoxes#114]
hi

i use moving box slider in my web site

this is address of my website

http://shokouhariya.ir

when clicked on 

محصولات

i use of moving box slider

and always see this error

stop script

script is slow

continue or stop script

and sometime browser hunged 

if anybody have information about moving box slider 

pls help me

thanks

**Comment by chriscoyier** [comment]
Doesn't seem to be using this script.
