### ISSUE TITLE
Can I use this plugin on commercial uses?

### ISSUE THREAD

**Issue by JimmyTodd** [CSS-Tricks/MovingBoxes#115]
Hello,
I have a question about this plugin license
Can i use it for commercial uses like part of a WordPress theme on market like themeforest
If I can not, is there a paid commercial version to use?
Thank you :)

**Comment by Mottie** [comment]
I'm not a license guru but @chriscoyier picked a [LGPLv3 license](https://github.com/CSS-Tricks/MovingBoxes/blob/master/license.txt) for this project; so as far as I know this license does allow the plugin to be included in a commerically sale-able product. But I'd wait for Chris to chime in here.

**Comment by chriscoyier** [comment]
I would consider it http://css-tricks.com/license/

**Comment by JimmyTodd** [comment]
Thank you @chriscoyier license page telling me use any thing you made in css-tricks on anything and This generosity of you,
but some what http://css-tricks.com/license/ says contrary what LGPLv3 license i think!!

see http://www.gnu.org/licenses/gpl-faq.html#GPLCommercially

Why the plugin license not under creative commons http://creativecommons.org/licenses/by/3.0/, I think this license fit what you said in http://css-tricks.com/license/

Thank you for your kind reply

**Comment by chriscoyier** [comment]
The point: I don't care about licensing. 

If that's a problem for you, sorry, you'll have to use something else.
