### ISSUE TITLE
ie7 issue

### ISSUE THREAD

**Issue by hpatel25** [CSS-Tricks/MovingBoxes#12]
Is there a bug in the code that displays incorrectly in IE7?  It looks like the javascript code isn't loading correctly on that browser
www.lowcostwebdesignfirm.com

Thanks,
Hiren

**Comment by Mottie** [comment]
Hi hpatel25!

I don't have IE7 to test for bugs, but it works just fine in IE8 in compatibility mode. Is there a specific error or line number of the error that you are seeing?

**Comment by hpatel25** [comment]
I found it :) there's an extra comma in this line before the comment after the }. IE7 doesn't like it when you have extra commas in javascript code.

 navFormatter : function(index, panel){ return panel.find('h2 span').text(); } // function which gets nav text from span inside the panel header

**Comment by Mottie** [comment]
ahhh good... oh is it on that site or in the core code? I'm pretty sure I cleared out all those naughty extra commas from the code.

**Comment by hpatel25** [comment]
It's on the site. It was hiding from us all!
