### ISSUE TITLE
(window).scroll / ("body").scroll isnt working in chrome/safari

### ISSUE THREAD

**Issue by antony-k1208** [CSS-Tricks/MovingBoxes#120]
I wanna add a scroll to top button to my website, but the event binding of (window).scroll{()}; doesnt seem to work. So ive changed it to $("body").scroll(function() {}); which works in every browser, only chrome/safari arent working. To which element i can bind the scroll event, to solve my problem?

**Comment by antony-k1208** [comment]
$('html, body').scrollTop(), $(document).scrollTop() and $(window).scrollTop() return always 0...

**Comment by JamyGolden** [comment]
http://api.jquery.com/scrollTop/ - $('html').scrollTop() and $('body').scrollTop() should return 0.

This should scroll to the top of the page

```
$('html, body').animate({
    scrollTop: 0
});
```

**Comment by antony-k1208** [comment]
No it shouldnt return 0. Otherwise how can u implement a scroll to top image which should only displayed if the user is scrolling the page to a certain amount?
Check the values in FF i.e. and see the result.

Anyway your solution isnt working for me in chrome. Other suggestions?

**Comment by JamyGolden** [comment]
```
$(window).scrollTop()
```

I think that should do what you're looking for.

As for the animate, it should work in all browsers: http://jsfiddle.net/m4TJt/

**Comment by antony-k1208** [comment]
Yeah thanks. I found the mistake, it was because of a wrong body,html css rule...

**Comment by ziplizard** [comment]
Do you recall the wrong body,html CSS rule? I think I'm having the same problem and cannot track it down.

**Comment by antony-k1208** [comment]
sorry for the delay.

I think it was something like that I had a full inline div (in size of the body) and got in trouble with inner / outer divs.

**Comment by AnilKumarSahoo** [comment]
Thanks a lot.......Superb.

After spent 2 days I got the solution because of this code. It's Simple but useful. This is working in every browser as well, So once again thanks...........

**Comment by alexlevn** [comment]
Thks, it took me 1 day.

**Comment by ivanVanelov** [comment]
Just to share some curious info. I had the same problem and apparently if the body has height: 100% set from the css the method will always return zero

**Comment by otinanaipali** [comment]
@ivanVanelov You saved my sanity... Thanks!

**Comment by pramacha** [comment]
@ivanVanelov Thank you so much!
