### ISSUE TITLE
Wrong height when use MovingBoxes within a tab content

### ISSUE THREAD

**Issue by saosangmo** [CSS-Tricks/MovingBoxes#126]
![screen shot 2013-12-16 at 11 09 25 pm](https://f.cloud.github.com/assets/4606931/1755935/776097a6-666c-11e3-8ae0-ca2a37c38800.png)
I am use a simple jquery tab to play MovingBoxes and try some css hack but not successfull. 

You can see it here http://koolbike.vn/xe-may-dien-dmn24-7

**Comment by Mottie** [comment]
Hi @saosangmo!

Wow sorry, I have no idea how I missed this issue. The solution would be to refresh MovingBoxes when the tab becomes visible/active.

``` js
$('#boxes').movingBoxes();
```

I didn't get a chance to see if that solved your issue since it appears that it is no longer being used. Sorry.

**Comment by saosangmo** [comment]
In the next time, I will implement your nice plugin with this solution.
Thank you
