### ISSUE TITLE
Re-charge the slider

### ISSUE THREAD

**Issue by brokoly250** [CSS-Tricks/MovingBoxes#127]
Hi, Im trying to make the slider loop infinite automatically, without using arrows.

When the page is loaded it makes only 1 transition but i need it automatically with every items of the list and then start since the beggining again.

Thank you very much !

**Comment by Mottie** [comment]
Hi @brokoly250!

Do you mean [a slideshow](http://jsfiddle.net/jMXx3/2885/)? This demo is from the main [wiki page](https://github.com/CSS-Tricks/MovingBoxes/wiki) under Demos > Other.

**Comment by brokoly250** [comment]
Thank you very much, that is what i wanted to do. It helped me a lot !! :D

**Comment by Mottie** [comment]
You're welcome!
