### ISSUE TITLE
Web Page scrolls to slider div

### ISSUE THREAD

**Issue by osCMattiFinn** [CSS-Tricks/MovingBoxes#13]
If movingboxes is placed toward the bottom of a web page, when a user first opens the page the page is scrolled to the movingboxes div (similar to a hash link)|, even when hashTags is set to false.

**Comment by Mottie** [comment]
Hi osCMattiFinn!

Thanks for pointing out this problem. It should now be fixed in version 1.7.1.  :)

**Comment by osCMattiFinn** [comment]
Yeah, thats good now.

Thanks!
