### ISSUE TITLE
With fewer than 3 items, images are truncated

### ISSUE THREAD

**Issue by fgosfacdjtq** [CSS-Tricks/MovingBoxes#19]
1. Setup an image carousel with one image in it.  
2. Use any parameters to initialize the carousel
3. Notice that part of the image is hidden by the generated CSS

The problem is that the width of mb-scrollContainer is too small when there are few items.  My short terms fix was to change lines 61-67 to this:

```
        // make scrollContainer wide enough to contain all the panels
        var width = (base.curWidth + 50) * base.totalPanels;
        width = Math.max(width,(base.curWidth + 50) * 3);
        base.$container.css({
            position : 'absolute',
            width    : width,
            height   : Math.max.apply( this, base.heights )
        });
```

**Comment by Mottie** [comment]
Hi Fgosfacdjtq!

This should be fixed in v2.0.1... all that was needed was to change the `+ 50` to `+ 100`. Thanks for bringing this to our attention.
