### ISSUE TITLE
Centering the images in the area.

### ISSUE THREAD

**Issue by gfe-morris** [CSS-Tricks/MovingBoxes#2]
I discovered that if you have smaller images and the imagesize of the smaller ones differs stronger from big ones you'll get problems with centering the images because there is a bug in calculating the center in the script. It calculates the center of the scroll and substracts the half of the small images instead of the big ones.

My fix looks like this:
Around line 105 it looks like this:
var leftValue = base.$el.find('.scroll').innerWidth() / 2 - panels.eq(curPanel-1).outerWidth() / 2;
you have to replace it with this:
var leftValue = base.$el.find('.scroll').innerWidth() / 2 - base.options.curImgWidth / 2;

**Comment by Mottie** [comment]
Fixed in the latest version.
