### ISSUE TITLE
[Enhancement] autoplay from random pane

### ISSUE THREAD

**Issue by aeltester** [CSS-Tricks/MovingBoxes#21]
Before this became a plugin, this: http://webdesignandsuch.com/set-the-jquery-moving-boxes-slider-to-autoplay/
worked well to have it autoplay. This: http://tc.eserver.org/js/slider.js
had enabled random startPane.
With the new design as a Plugin it's much better integrated in my page but I'm too noob to make those enhancements to the plugin.
Any help would be greatly appreciated!

**Comment by Mottie** [comment]
Hi Aeltester!

Actually someone just posted how they did this in the [CSS-Tricks forum](http://css-tricks.com/forums/discussion/comment/43379/#Comment_43379), basically you can add this anywhere on your page:

```
setInterval( function() {$('.mb-right').click();}, 5000 );
```

The main difference from the post you linked and this code is that the button class names have changed from ".left" and ".right" to ".mb-left" and ".mb-right"

**Comment by aeltester** [comment]
genius!
Thank you so much, it works flawlessly :)
now I'll try to make it a var to centralize settings...
Did you consider adding this feature to the plugin yet?

**Comment by aeltester** [comment]
Hi Mottie!
Thanks again for helping me out with that one. Now I do have discovered a flaw: if I scroll down so that the slider is invisible and the setInterval makes the slider change, the page jumps up to the slider again. From the top of your head, can you think of a way to suppress this?

**Comment by Mottie** [comment]
Hi Aeltester!

Well... this link inside the MovingBoxes gets focus when the panel comes into view to make it easier for users who use the keyboard to navigate (tab key) through the panels. Maybe I should just remove it completely since it's been causing so much trouble.

Basically, just comment out or remove line 241:

```
base.$panels.eq(curPanel - 1).find('a').focus();
```

I'll look into adding some kind of slideshow feature in the next version.

**Comment by aeltester** [comment]
Hi Mottie,
you're awesome!
commenting both lines below did the trick!

a.$panels.eq(b - 1).find("a").focus();
a.$window.scrollTop(0)

Thank you so much.
