### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by CtownChawks** [CSS-Tricks/MovingBoxes#25]
I was just wondering if there is an easy way to put multiple instances of the Moving Boxes on a single page. I have tried renaming the file and the id's and it doesn't seem to work.
Thanks for your help

**Comment by Mottie** [comment]
Hi CtownChawks!

Did you look at the [demo page](http://chriscoyier.github.com/MovingBoxes/) source? There are two Moving Boxes on that page. Just follow that example.
