### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by sibtulhasnain** [CSS-Tricks/MovingBoxes#26]
Sir,

How  can i increase the width and add more then one moving box in it

Regards:
Sibtul Hasnain

**Comment by Mottie** [comment]
Hi Sibtulhasnain!

This isn't built into MovingBoxes, but I'll look into it when I have time. In the mean time, I have given [AnythingSlider](https://github.com/ProLoser/AnythingSlider) the ability to show multiple slides at once, so maybe this will work for you? If not, you might have to wait for me to figure out how to add this functionality to MovingBoxes - but like I said, when I get more time.

**Comment by Mottie** [comment]
I'm going to close this issue as I [opened a similar issue](https://github.com/chriscoyier/MovingBoxes/issues/27) (my mistake)... I would like to make it expand to fit inside of it's container instead of setting a width or making it 100% width.
