### ISSUE TITLE
Loop the slides

### ISSUE THREAD

**Issue by Mottie** [CSS-Tricks/MovingBoxes#28]
Many requests to loop the slideshow instead of rewinding... I'll look into it when I get time.

**Comment by color2life** [comment]
Hey How this is possible... to looop it.

**Comment by Mottie** [comment]
Currently the boxes don't loop. When you get to the end, it rewinds the boxes to start at the beginning again. In order to make it loop back to the beginning, we either need to keep moving the first box to the end, or make a copy of the first box and stick it on the end then rewind it super fast so you can't tell. I'm starting to think about just making an extension for AnythingSlider to act like this plugin since so much of the code is the same.

**Comment by kaushal123** [comment]
Any one solved this issue?

**Comment by Mottie** [comment]
I've haven't looked at this ability yet, I've been busy with other things... maybe I'll try to work on it this weekend.

**Comment by Mottie** [comment]
Update: I have added the ability to loop the panels, but I'm trying to fix problems that occur with alignment when dynamically adding and removing panels. So please stay tuned!

**Comment by kaushal123** [comment]
Thanks very much Mottie for the update. U are awesome.

**Comment by aguieb** [comment]
Thanks Mottie for the update.

**Comment by aguieb** [comment]
Mottie - You mentioned that you were able to loop the panels... I am curious how you did it. Is it possible for you to send me the code that made that possible even though you are still trying to fix the add and remove panal issue?

thanks in advance

angel.guieb@gmail.com

**Comment by paudelvinay** [comment]
Hey guys, if  you have already solved the loop issue, please let me know.

**Comment by aguieb** [comment]
will do

On Wed, Nov 9, 2011 at 2:48 AM, Vinay paudel <
reply@reply.github.com>wrote:

> Hey guys, if  you have already solved the loop issue, please let me know.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/chriscoyier/MovingBoxes/issues/28#issuecomment-2678843

## 

Angel Guieb
815-893-9032

**Comment by Mottie** [comment]
And there you have it... infinite panels now in version 2.2 :)
