### ISSUE TITLE
Make into a WordPress Plugin

### ISSUE THREAD

**Issue by Mottie** [CSS-Tricks/MovingBoxes#3]
If anyone knows how to make this jQuery plugin into a WordPress plugin, it would be greatly appreciated :)

I would attempt it (http://www.jdmweb.com/resources/jquery_to_wordpress_plugin), but I don't have any easy way to test my work.

**Comment by jonhorner** [comment]
Still interested in having a WordPress plug in for Moving Boxes? I'm happy to set one up.

**Comment by Mottie** [comment]
Hi Craftyhub!

Yes, that would be fantastic! I'm a noob with Wordpress and Wordpress plugins so any help in this area would be great :)

I plan on working on this plugin (in about two weeks, when I have time) to add some of the proposed enhancements. So don't "finalize" all of the options just yet ;)

**Comment by jonhorner** [comment]
OK, I'll start putting it together. I'll be doing it in my spare time anyway so will probably take more than a couple weeks to complete.

**Comment by alicapwn** [comment]
Were you two able to put one together? I'd really like to use it.

**Comment by jonhorner** [comment]
Sorry, it's not completed yet. Been on Holiday and pretty busy at the moment. I'll take a look at it over the weekend if I get chance.

Mottie, I see you've updated the MovingBoxes code. Do you still any work to do on it or is that all for now?

**Comment by Mottie** [comment]
I was planning on looking into expanding the width and maybe trying to figure out the infinite loop (both open issues), but I too have been busy with other things. So I don't think it'll get done any time soon.

**Comment by jonhorner** [comment]
Plugin now available on wordpress: http://wordpress.org/extend/plugins/movingboxes-wp/ or search for 'movingboxes' in your 'Install Plugins' page of your site admin section.

**Comment by Mottie** [comment]
Awesome!
