### ISSUE TITLE
Post Sort Function

### ISSUE THREAD

**Issue by roberthuttinger** [CSS-Tricks/MovingBoxes#30]
I am trying to use sortify to sort the entries. After sorting I can call movingBoxes but when the yget sorted they retain the original css that was applied. IE: if element one becomes element 3, then what is now element 3 has padding on the left side. 

I have also tried to reload the dataset via jquery .get(), but pleasing to share how to re-init the entire list after performing an action. I am not a jquery guru, but isnt movingBoxes set to initialize on docuemnt.ready? Is there a method I can use to re-init? 

Love the plug!

cheers.bo

**Comment by Mottie** [comment]
Hi Roberthuttinger!

I found the problem and updated MovingBoxes to version 2.0.5. Here is [a demo](http://jsfiddle.net/Mottie/qh4Zj/) with a sort button so you can check it out in action

Thanks for reporting this problem!

**Comment by roberthuttinger** [comment]
simple and to the point. my newness to jquery prevented me from seeing the obvious, sort, then re-insert the elements! youre the best!
