### ISSUE TITLE
Flickering YouTubez

### ISSUE THREAD

**Issue by roberthuttinger** [CSS-Tricks/MovingBoxes#31]
This was a very crude fix on my part, but I was experiencing flickering with youtube video I have embedded. I was able to solve the problem by suppressing the grow shrink functions. I still had the flickering issue. after some code tracing I discovered the when jQuery touched the DOM looking at the em height of the text, the youtube embed was reacting with a reload. 

Could there be an option to have no resizing whatever, and just be a simple slider for an instance?

cheers!
bo huttinger

**Comment by Mottie** [comment]
Hi Robert!

Yeah, I've noticed that problem recently and it only seems to occur in Firefox. If I change the code a bit I might be able to fix it, but you still wouldn't be able to use the resizing at all. And in all honesty if you want a simple slider with no resizing, take a look at [AnythingSlider](https://github.com/ProLoser/AnythingSlider). It can do everything but the resizing and gives you control over the video as well.

I think I'll submit a jQuery bug report.. thanks for figuring out it was the em height causing this problem, I hadn't had a chance to investigate it that thoroughly yet.

**Comment by roberthuttinger** [comment]
There is certainly a place for choosing the right tool for the right job, however, I see that you are invested in your product and want to support you in your effort, to that end, I wanted to submit this report. I am sure there are other simple use sliders, but as someone who develops tools on a regular basis, I would prefer to stick with a tool and just set a flag for an instance of the application to prevent the resizing. I think in most other cases, I would use the resizing.
cheers.bo huttinger

**Comment by Mottie** [comment]
No worries :)

I work on AnythingSlider as well and essentially the code for this plugin and AnythingSlider are becoming more and more similar. I will fix it so if the `reducedSize` option is `1` it will bypass the animation... give me a min ;)

**Comment by roberthuttinger** [comment]
Rocks rock hard, but you rock harder!! :D

**Comment by Mottie** [comment]
Done :P
