### ISSUE TITLE
how to call jquery on any other event?

### ISSUE THREAD

**Issue by KarunaHotlani** [CSS-Tricks/MovingBoxes#32]
Hi,

This is really very nice jquery plugin. But I have one problem.

What I am doing is, I am previewing htmls in this scrollbar (instead of images). after previewing html,I want to change any of that html (change text of html or change image) which gets update in database and preview the updated html fetched from database on this scrollbar. I am updating these htmls using ajax.
 Now when I am previewing updated html using ajax page is not reloading where as your jquery calls only when page loads. So I want to know how can i call this jquery on any event. like onclick or etc.

**Comment by Mottie** [comment]
Hi KarunaHotlani!

I had to read this several times, but I think what you are asking is how do you call a jQuery function after you've updated MovingBoxes using ajax.

I'm only guessing that what you are looking for is to use the ajax callback method... the [`load` event](http://api.jquery.com/load-event/) can be used to load content into a panel, then the callback can apply click events or whatever once the load is complete. For example:

``` javascript
// get new panel content
$.get('ajax/test.html', function(data){
  $('#slider').find('li:eq(0)')
    .html(data)
    .find('.popup').click(function(){
      // do something
    })
    .movingBoxes(); // make the plugin update
});
```

**Comment by Mottie** [comment]
I'm guessing this solved your problem, so I'm closing this issue.

**Comment by KarunaHotlani** [comment]
I never tried that solution, as such I moved out to some other design.
May be later on I will again do that. At that time I will check that solution.
By the way thanks your help.

Thank You
Karuna Hotlani
eMbience Inc.

-----Original Message-----
