### ISSUE TITLE
Make the first slide be selected first (not the middle one)

### ISSUE THREAD

**Issue by gongbaojiding** [CSS-Tricks/MovingBoxes#33]
As the title says, is there any way to make the actual first slide be selected first? currently when I load the page the slider always automatically slides to the middle. 

If possible I like it to load the first slide and then stay and not move unless clicked.

Appreciate any help with this.

**Comment by Mottie** [comment]
Did you set the `startPanel` to `1`?

Here is a [demo](http://jsfiddle.net/Mottie/ePDSw/1/)

**Comment by Mottie** [comment]
I'm going to assume the issue has been resolved. Feel free to reopen it if you are still having problems.

**Comment by webbird** [comment]
I am having the same problem with v2.1.4. When loading the page, the slider always slides to the middle, no matter how startPanel is set. Firefox v7.0.1

**Comment by Mottie** [comment]
@webbird Could you share a link to the page with the issue. It's difficult to troubleshoot without any thing to work from.

**Comment by webbird** [comment]
I will create one. Stay tuned. ;)

**Comment by aguieb** [comment]
Set hash to false. When that is done your first pic will be selected when your browser refreshes.

**Comment by webbird** [comment]
Like this?

$('#mboxes').movingBoxes({
            startPanel   : 1,
            width        : 500,       // overall width of movingBoxes
            hash         : false
        });

Doesn't work. :/

**Comment by webbird** [comment]
Argh! I think I've got it! I missed the "slider1=<number>" GET param in the URI, so whenever I hit "Reload" this was sent, too. I'm sorry! :(

**Comment by Mottie** [comment]
Duh, I should have thought of that. Thanks @aguieb!
