### ISSUE TITLE
Arrow buttons don't work

### ISSUE THREAD

**Issue by jmarx** [CSS-Tricks/MovingBoxes#34]
Has anyone else experienced an issue where the right and left arrow buttons don't work? But you can still scroll through the photos by clicking directly on them? I would put in a link. But i want to ask first, The issue with putting a link in here is that the issue only happens intermittently. So I can't really troubleshoot like I normally would. So I'll just ask straight out, has anyone experienced this as well? I work for a media company and we're willing to provide compensation for someone who can help us troubleshoot this. I'm at my wit's end.

**Comment by Mottie** [comment]
Hi JMarx!

You know I just noticed the same thing last week in a jsFiddle demo but when I switched browsers it started working so I thought maybe my browser was acting wonky. Anyway, long story short, it was a problem with MovingBoxes initializing on a slide other than the first, via hash tags or initialization code. So I've fixed it in the latest version 2.1.2.

**Comment by jmarx** [comment]
Thanks! I'll give it a try first thing tomorrow/ Thanks for getting to that so fast!

**Comment by jmarx** [comment]
Thanks Chris! That works great! Is there any way to keep the arrows static as you move from photo to photo? So they don't slide up and down? But you can still navigate?

**Comment by jmarx** [comment]
Also .. do you have a paypal/donation email? I'd like to make a donation.

**Comment by Mottie** [comment]
Hi JMarx!

If you want to fix the height so the arrows don't move up and down, just set the `fixedHeight` option to `true`.

And I don't think neither Chris nor I has a paypal button, so how about you just "pay it forward" ;)

Rob (aka Mottie)

**Comment by jmarx** [comment]
Thanks, Rob, I did that and it worked well.
I'm not sure what you mean by "pay it forward", but if you just let me know if you have an email address I can paypal to, that would be cool. Otherwise, if I can help you guys in any other way, don't hesitate to ask.

**Comment by Mottie** [comment]
["Pay it Forward"](http://www.urbandictionary.com/define.php?term=pay+it+forward) is basically a term to ask you to help out someone in need. So there is no need to donate anything back to me :)

**Comment by centinex** [comment]
Hi Mottie (and as I said in another thread, thanks for your job ;) ),
Strangely for me, this issue is not fixed. Sometime arrows do not work, and it do not seems to be related to anything. Sometime a refresh do fix the issue, sometime it do not. Very strange.
It do seems to occurs more often when the browser is on hard load (many images to load, and the such) but I'm not sure. I'm using more than one MovingBoxes and the same page, maybe the issue is linked to this kind of usage?
