### ISSUE TITLE
make only selected slide link clicable 

### ISSUE THREAD

**Issue by eXXon48** [CSS-Tricks/MovingBoxes#36]
all that I need to do its make links in the slides unclicable until the slide became selected
i try something like this 

$("#slider li").not(".current").find("a").live("click",function(event){event.preventDefault();}); 

but this don't work

also i find out that when i clear cashe  slider stops on first slide and buttons don't work, but when i click on left or right  slide it sliding out as usual

**Comment by Mottie** [comment]
Try this ([demo](http://jsfiddle.net/Mottie/r6yWC/1/)):

``` javascript
$("#slider a").bind("click",function(event){
    if ($(this).closest('.mb-panel').is('.current')) {
        // allow click
        return;
    } else {
        // prevent link from working - click still switches panels.
        event.preventDefault();
    }
});
```

**Comment by eXXon48** [comment]
about buttons all works fine, just update  jquery to latest version also updated moving boxes to latest

but still cant prevent click function on links that not in current page (slide)

**Comment by eXXon48** [comment]
Thank you very much for your quick response, now it works as it should

also, if you using ajax load content into moving boxes its better to chose live() instead bind()
$("#slider a").live("click",function(event){
..............
});

**Comment by Mottie** [comment]
Update: This should no longer be an issue in version 2.2.3+.
