### ISSUE TITLE
How to cerculate this slider?

### ISSUE THREAD

**Issue by kaushal123** [CSS-Tricks/MovingBoxes#39]
At first image, when it is in center, last image should be displayed at left side & at last, the first should be displayed at right side.
Any Help?
Thanks.

**Comment by Mottie** [comment]
I'm going to close this issue since it is essentially the same as [issue #28](https://github.com/chriscoyier/MovingBoxes/issues/28)

**Comment by kaushal123** [comment]
Thanks Mottie for your help. But yes if this issue solved as soon as possible then it would be good.
