### ISSUE TITLE
Different panel heights

### ISSUE THREAD

**Issue by dlopez2000** [CSS-Tricks/MovingBoxes#4]
I have panels that were different heights.  To make the container hold the tallest panel without cropping (versus using the height of the first panel), I first adding a jQuery plugin (I'm no expert, so not sure if this is the best way to do it):

   jQuery.fn.maxOuterHeight = function(){
        var max = 0;
        this.each(function() {
                max = Math.max( max, $(this).outerHeight() );
        });
        return max;
};

then right after defining base.panels:

```
        base.tallest = base.panels.maxOuterHeight();
```

and then in setting scrollContainer:

```
        base.container = base.$el.find('.scrollContainer').css({
            position : 'relative',
            width    : (base.curWidth + 50) * base.totalPanels,
            height   : base.tallest
        });
```

This seems to work for me.

**Comment by Mottie** [comment]
Nice! I was wondering though, how much of a different size is the panel? Do you have a demo or can you share a link of what you have now?

**Comment by dlopez2000** [comment]
I don't have a demo I can link to right now, but I'll see if I can set one up soon.

All the demos of MovingBoxes I've seen used a tiny teaser text that always fit on one line.  I have short text, but it can vary between 2 and 4 lines long.  My code is working well for that scenario (where the tallest panel is not first in the sequence).

**Comment by Mottie** [comment]
I just pushed v1.5 with code to adjust the panel height automatically :P. Thanks again!

**Comment by Mottie** [comment]
@dlopez2000: I just pushed v1.5.1 which allows you to set a "fixedHeight" variable so it won't auto-adjust :P
