### ISSUE TITLE
Back navigate panel click doesn't work when Continues sliding is turned on

### ISSUE THREAD

**Issue by aguieb** [CSS-Tricks/MovingBoxes#44]
Thanks for making the Continues sliding work!

But I did quickly notice that when wrap is set to true, clicking the left panel to navigate back doesn't work. Only way to navigate back is to click the arrow?
Clicking the right panel to move forward does work....

**Comment by Mottie** [comment]
Oops! Ok this bug has been fixed in v2.2.1
