### ISSUE TITLE
How can I use MovingBoxes Control with Database

### ISSUE THREAD

**Issue by hassaancs** [CSS-Tricks/MovingBoxes#47]
IS this possible to Get the results (Pictures, other info) from Databases like Sql Server?
When I try to get data from Db it starts firing Exceptions because of Panels... Can anyone help me in this regards?

**Comment by Mottie** [comment]
How are you adding panels to MovingBoxes? If you look at the main demo, you'll see that you can dynamically add and remove panels, but you'll need to call the plugin function again to update the slider:

``` javascript
$('#slider')
    .append('<li><h2>Header</h2><img src="my-image.jpg"><p>info</p></li>')
    .movingBoxes();
```

**Comment by hassaancs** [comment]
I think I ve an older version of the Control. Many things are changed in the download available here and the one which I ve. I will try that on Newer version and let you know about it. Thanks For Reply.
