### ISSUE TITLE
When arriving at a panel from a URL (eg ...'#&slider1=2'), that panel does not receive the 'current' class

### ISSUE THREAD

**Issue by duncanjbrown** [CSS-Tricks/MovingBoxes#53]
If one scrolls off the panel, and then back onto it, it works again.

Thanks for this excellent plugin.

**Comment by Mottie** [comment]
Could you please provide an example? I just tested this on the main demo page: [http://chriscoyier.github.com/MovingBoxes/#&slider2=4&slider1=3](http://chriscoyier.github.com/MovingBoxes/#&slider2=4&slider1=3) and the current panel in both sliders has the "current" class name applied. The easiest way to tell is that the "current" class name has the cursor set to auto, so it's an arrow, whereas the non-current panels have the `cursor:pointer` (hand) applied.

**Comment by duncanjbrown** [comment]
Hi Mottie. Thanks for responding. I am so sorry, but now I can't even replicate the problem - ie it's working fine. Clearly eveything is in fact ok. Apologies for the false alarm.

**Comment by Mottie** [comment]
No problem, I'm glad it's working! :)
