### ISSUE TITLE
[left|right] arrow image are not displayed in IE6

### ISSUE THREAD

**Issue by mumumu** [CSS-Tricks/MovingBoxes#6]
First, This issue can be reproduced in IE6 only. Please close this soon if you are NOT going to support IE6 officially.

Description: [left|right] arrow png images are not displayed in IE6
How reproducible: Always
How to reproduce: display index.html with IE6.
Expected result: [left|right]_arrow.png can be displayed.
Aucual result: They are not displayed, but we can click them and scroll images.

How to fix: This issus is caused by the following css in movingboxes.css, background transparent setting.

```
 /*** Left & Right Navigation Arrows ***/
 a.scrollButtons {
     display: block;
     width: 45px;
     height: 58px;
     background: transparent no-repeat top center; /*** this causes a probrem in IE6 */
```

We can fix this by patching IE6 specific css hacks. If you can accept, I'll send you a pull request.
Best Regards.

**Comment by Mottie** [comment]
I have no way of testing in IE6, but if only css is required then sure, share it please. I wouldn't think a hack is needed because I only recently changed the arrow image to include normal and hover states. Is it because it is a png image? I could easily provide a gif.

**Comment by Mottie** [comment]
In the latest version 1.6.2, I combined the arrow images and made both a "png" and "gif". So, if you want to add some conditional comments to target IE6 (http://www.quirksmode.org/css/condcom.html) to change the image, that might also fix your problem.

**Comment by osCMattiFinn** [comment]
IE6 does not understand the CSS:  background:transparent and can do some strange things when its used.

**Comment by Mottie** [comment]
Hmm, I hadn't read this issue in a while, I guess Mumumu added some css, but not the solution. Is there a simple solution? I don't have IE6 to test on, so if mumumu is still reading this, just post the fix here... I'm still not sure how to deal with pull requests LOL ;)

**Comment by Mottie** [comment]
Try the newly added separate IE stylesheet... going to close this issue since it seems resolved.
