### ISSUE TITLE
Weird Scrolling Issue

### ISSUE THREAD

**Issue by bbar** [CSS-Tricks/MovingBoxes#60]
If wrap is set to true, then clicking on any hyperlink nested inside the `<div>` or `<li>` triggers the script to scroll forward.

**Comment by Mottie** [comment]
Hi bbar!

Thanks for reporting this, I'll have it fixed in the next update.

**Comment by bbar** [comment]
Sweet! Btw, MovingBoxes is a really useful, versatile script!

**Comment by Mottie** [comment]
Ok, this problem should be fixed in v2.2.3.
