### ISSUE TITLE
MovingBoxes with Mootools in Chrome

### ISSUE THREAD

**Issue by kaaan** [CSS-Tricks/MovingBoxes#64]
I tried to use MovingBoxes on a Joomal website and it works great in most browsers but not in Chrome. The left an right arrows don't work. When I remove <jdoc:include type="head" /> in the template it works fine. <jdoc:include type="head" /> includes Mootools so this could be the problem. I still want to use <jdoc:include type="head" /> because in inserts many other things like title-tag. Any idea how to solve it?

**Comment by Mottie** [comment]
Hi Kaaan!

Sorry for the delay, I was extremely busy last week. Could you share a link to the site where you are having problems please. I can only guess at what problem you might be having and I'm not very familiar with Joomla.

**Comment by Mottie** [comment]
Has this been resolved? Was jQuery set using `jQuery.noConflict();`?

**Comment by Mottie** [comment]
I'm guessing this has been resolved. Please feel free to reopen this issue if you continue to have problems.
