### ISSUE TITLE
Moving Box not using JQuery

### ISSUE THREAD

**Issue by aguieb** [CSS-Tricks/MovingBoxes#65]
Your moving box is very impressive but I was wondering if this can be done without using JQuery. Is that possible? If so, can you point me to the right direction? I have a client who does not like to use JQuery in his website… Any advice will do.
Thanks in advance!!!

**Comment by Mottie** [comment]
Hi aguieb!

Sadly, I don't have the time or the patience to completely rewrite MovingBoxes to work without jQuery.

I'm sure there are other sliders that are somewhat similar that don't require jQuery. But honestly, I think if you chat with the client and explain the minimal overhead that jQuery requires, that it's hosted on google's CDN and the number of sites that actually utilize jQuery maybe you can convince them to change their minds. If not, try smacking them with a mackerel.

**Comment by aguieb** [comment]
Thanks for your quick response. I will probably try to mimic what you have done with the slider without using JQuery. Once I get this done, I will pass you my source code. Do you have any technical document on how you wrote the slide beside the comments you have in your source code? Also what JQuiry library did you use for your slider? Thanks in advance!

**Comment by Mottie** [comment]
Actually Chris Coyier started this project. Here is the [original article](http://css-tricks.com/moving-boxes/) he posted.

It looks like the original script can be seen if you view the source of [this demo](http://css-tricks.com/examples/MovingBoxes/) - [link to file](http://css-tricks.com/examples/MovingBoxes/js/slider.js)

But really, if the size of jQuery is the issue, do you know about [zepto](https://github.com/madrobby/zepto)? It's like jQuery but super minified, but missing some functions.
