### ISSUE TITLE
callback on final panel

### ISSUE THREAD

**Issue by dubdesign** [CSS-Tricks/MovingBoxes#75]
again not an issue but a question/request.

Is it possible to trigger a function when the slider gets to the final panel (with wrap set to false)?

as an example it could open up a modal dialog box saying thank you for watching this slideshow, would you like to watch it again? I'm wanting to do something slightly different but i thought that was probably the best example to explain.

**Comment by Mottie** [comment]
All you need to do is use the `completed` callback and check the wrap option value and which panel is showing ([demo](http://jsfiddle.net/Mottie/jMXx3/993/)):

``` javascript
$('#slider').movingBoxes({

    completed: function(e, slider, tar){
        if (!slider.options.wrap && tar === slider.totalPanels){
            alert('You are on the last panel');
        }
    }

});​
```

**Comment by dubdesign** [comment]
perfect, exactly what i was looking for thanks
