### ISSUE TITLE
Custom Hashtag

### ISSUE THREAD

**Issue by Alfazo** [CSS-Tricks/MovingBoxes#78]
Hi,

I'm looking for a way to build a custom hash for the URL, like in anythingSlider (https://github.com/ProLoser/AnythingSlider/wiki/Navigation-options#wiki-hashtags).

What I'd like to do, is set each Hash to a dynamically generated H6 tag — or alternatively, the li/div panel name.

**Comment by Mottie** [comment]
This is already part of MovingBoxes... I don't have a demo, but if say I add an ID to the h2 tag:

``` html
<li>
    <img src="demo/3.jpg" alt="picture">
    <h2 id="news-3">News Heading</h2>
    <p>Add a short exerpt here... <a href="http://flickr.com/photos/ruudvanleeuwen/468309897/">more</a></p>
</li>
```

Then added a `#news-3` hash to the URL, it will make that panel visible on page initialization.

**Comment by Alfazo** [comment]
Thanks for the reply!

I understand how that works (similar to the #astronaut demo), but I need to get the hash working so that it updates the URL to the new hash when using navigation arrows. Also, using this method, the browser automatically scrolls to the top of the slideshow, which is a problem as I'm using ScrollTop to set the page to a specific place on load/refresh/next/previous arrow.

**Comment by Mottie** [comment]
When you set the hash the browsers automatically changes the scrollTop, so I'm not sure what you are trying to do. But, I did make a [demo for AnythingSlider](http://jsfiddle.net/Mottie/VM8XG/4488/) for this [StackOverflow question](http://stackoverflow.com/questions/8887979/how-can-i-change-the-hashtag-names-in-anythingslider/8889364#8889364) which adds a prefix to the hash tag name so the browser won't scroll... it should be relatively easy to modify it to work with MovingBoxes by just changing the callback function names.

If the above doesn't work, could you please share a demo... it would make it easier for me to modify it than to start from scratch.

**Comment by Alfazo** [comment]
Thanks, I've tried implementing that code into movingBoxes before, and again just now, but couldn't get it to work… I'm still getting the default hashtags. What You have posted is exactly what I need to achieve, I just can't work out how to do it.

(as a side note, I have got that above demo working in anythingSlider before, but unfortunately I can't use it for this project).

**Comment by Mottie** [comment]
Ok, I've made a [MovingBoxes demo](http://jsfiddle.net/Mottie/jMXx3/1401/) for you that renames the id's so the page won't jump. Try the link below to see it jump to Yin's panel

[http://jsfiddle.net/Mottie/jMXx3/1401/show/#yin](http://jsfiddle.net/Mottie/jMXx3/1401/show/#yin) .

**Comment by Alfazo** [comment]
Perfect! Thanks Mottie, you absolute legend.
