### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by Alfazo** [CSS-Tricks/MovingBoxes#80]
Hi,

is there any way to make a delay on the "next/previous" animation, like in anythingSlider?

I tried adding a delay to line 343 of the movingboxes.js, but to no avail.

**Comment by Mottie** [comment]
You need a delay before animation?

**Comment by Alfazo** [comment]
Yeah, I'm using beforeAnimation to call a scrolltop, which will move the page vertically before moving the slideshow horizontally. In anythingSlider, setting the 'delay' option to the same value as the scrolltop, which is the effect I'm trying to replicate with movingboxes.

**Comment by Mottie** [comment]
Ok, I'll look into adding this option.

**Comment by Alfazo** [comment]
Awesome, cheers!

**Comment by Mottie** [comment]
I added a delay option named `delayBeforeAnimate` in version 2.3. Sorry for taking so long to get this done!
