### ISSUE TITLE
Setting Nav arrows at an absolute location when width of box stage is at 100%

### ISSUE THREAD

**Issue by gbucha** [CSS-Tricks/MovingBoxes#83]
I am using the script on a new website:
http://thejusticeconference.com/dev2012/

My issue is that I want the navigation arrows to be at an absolute location, but they move to different locations based upon the users browser width.

How can I just stick them to the edge of the current panel?

**Comment by Mottie** [comment]
Hi gbucha!

Sorry for not getting back earlier... maybe I'm not understanding, but it looks like the arrows are set using a negative margin or left or right of `-530px`. If I change that to `-510px` the arrows are flush with the current panel. It works, but I'm not sure if IE would like to do what you wanted... So, is that what you needed? Or am I missing something.

Very nice site by the way... I'm glad you've also found AnythingSlider useful :)

**Comment by gbucha** [comment]
I figured it out. 

Kindest regards,

Greg Buchanan
GelFuzion,Inc.
www.gelfuzion.com
V: 541-317-8616

**Comment by Mottie** [comment]
Ok! :)
