### ISSUE TITLE
IE9 doesn't minimize the images

### ISSUE THREAD

**Issue by chanel535** [CSS-Tricks/MovingBoxes#86]
Hi there,

I've been trying to fix this for days now, but for some reason the images are not resizing in IE9.
They look fine in all other browsers....
Does anyone know what the issue could be.
I am using the ie css file too...

**Comment by Mottie** [comment]
Hi chanel535!

I double checked and the [main demo](http://chriscoyier.github.com/MovingBoxes/index.html) appears to be working as expected in IE9. Would you please share the settings you are using or better yet, [modify this demo](http://jsfiddle.net/Mottie/jMXx3/).

One thing to check first, is if the `reducedSize` option is smaller than `1`. If it isn't, the images won't get smaller.

**Comment by chanel535** [comment]
Hi Mottie!

Thanks for getting back so fast!
I don't know if you're talking about my css or js settings.
The reducedSize option is set to 0.7 so that can't be the issue...
Maybe you could check my site in IE9?
The url is www.xarabi.com

**Comment by Mottie** [comment]
It looks like that page is being switched into quirks mode. Add the following to the head of the page and it should fix the problem:

``` html
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

**Comment by chanel535** [comment]
OMG!! You're right, that did the trick! 
Thank you so much, I probably wouldn't have figured this out by myself.
I really appreciate it!!
