### ISSUE TITLE
stoping images to auto expand when changing width of slider

### ISSUE THREAD

**Issue by sido74** [CSS-Tricks/MovingBoxes#87]
Hi there, I want to expand the width of the slider so i can show more images but when i do this the images auto expand and the height gets bigger to. Is there anyway of setting the images to a constrained size so that when expanding the width of the slider more images will show.

thanks

**Comment by Mottie** [comment]
Check out [this demo](http://jsfiddle.net/Mottie/jMXx3/)

If you change the size of the `#slider` but leave the `#slider li` width alone, it will make the view port bigger without resizing the panels. 

``` css
#slider {
    width: 300px;
}
#slider li {
    width: 150px;
}​
```

Is that what you wanted?

**Comment by sido74** [comment]
Yea that was what i was after, although the images when enlarged distort a lot, is there anyway to prevent his?

**Comment by Mottie** [comment]
I'm guessing that I answered your question in issue #88. If you continue to have problems, please feel free to post your question in the [CSS-Tricks forums](http://css-tricks.com/forums/discussions).
