### ISSUE TITLE
Having problems with my images becoming distorted 

### ISSUE THREAD

**Issue by sido74** [CSS-Tricks/MovingBoxes#88]
when applying my images into tho slider they become distorted, is there a certain way i should save my images? or a certain size? or will they always be distorted?

thanks

**Comment by Mottie** [comment]
MovingBoxes only changes the size of the slide. So if you don't do anything to your image, it will be effected by the `max-width:100%` css setting making the image shrink down proportionally.

So you can either set a fixed image size or only set the width/or height as a percentage, then the image will resize proportionally.

**Comment by Mottie** [comment]
I'm guessing that this problem has been resolved so I'm closing this issue. Please feel free to reopen it if you continue to have problems.
