### ISSUE TITLE
Get access to the .currentlyMoving status from outside

### ISSUE THREAD

**Issue by Olli** [CSS-Tricks/MovingBoxes#9]
Is it possible to get access to the movingstatus from outside to check if the boxes already moving or completed from a other script?

**Comment by Mottie** [comment]
Hi Olli!

You can get that value using the following:

```
$('.slider').data('movingBoxes').currentlyMoving
```

Actually you can get any of the values that way:

```
$('.slider').data('movingBoxes').{value}
```

If you want to get an option value, use this:

```
$('.slider').data('movingBoxes').options.{value}
```

From inside a triggered event:

```
$('.slider').bind('beforeAnimation',function(e, slider, tar){
    alert( 'moving? ' + slider.currentlyMoving ); // will always be true during this event
});
```

**Comment by Olli** [comment]
Oh! Thx :)
