### ISSUE TITLE
Moving Boxes and Twitter Issue?

### ISSUE THREAD

**Issue by odonnetp** [CSS-Tricks/MovingBoxes#93]
Hi all,

New to github but have a client using the moving boxes plugin on their site while also using a twitter widget. Anyways, our site is now showing tweets in reverse order, so instead of most recent tweet first, it is most recent tweet last. I've put the twitter code on its own blank page without anything else on it, and it works fine, so I don't suspect it is anything on Twitter's end. On the site with the moving boxes, it displays tweets backwards. Then, we had a page where the moving boxes ended up not working at all (maybe JS code didn't load fully or correctly, elements of moving boxes were like a vertical list) and the twitter widget worked correctly, with tweets in the correct order.

Has anyone else had a conflict using moving boxes with a twitter widget feed and experienced similar issues? Any ideas to a possible solution?

**Comment by Mottie** [comment]
Hi odonnetp!

It sounds like there might be a javascript error breaking some scripts on the page. Press F12 in your browser and go to the console. It will show you any javascript errors. If you could share what error you see, it would help me troubleshoot the problem. Better yet, if you could share a demo or link to the page in question it would help even more.

**Comment by odonnetp** [comment]
I did that, only javascript errors seem to be from FB. so maybe it's the FB code then?? Here's the site: http://bcattv.org/ You'll see the moving boxes on the homepage and some other pages. But, the twitter feed in the left side column has the tweets backwards. If you take our twitter code and put it on its own page, tweets show with most recent tweet first.

Thanks in advance for any help!

**Comment by Mottie** [comment]
Hmm, I don't any error and honestly I don't think this issue has anything to do with MovingBoxes. Because, when I look at [this page](http://bcattv.org/bnews/archives/), the tweets appear to be reversed in order but MovingBoxes isn't being used.

**Comment by odonnetp** [comment]
Seems you are right. It ended up being a js conflict with a different file. Thanks for your help though! Great functionality
