### ISSUE TITLE
please remove the BOM

### ISSUE THREAD

**Issue by ffissore** [CSS-Tricks/MovingBoxes#94]
at the beginning of the js file jquery.movingboxes.js there is teh BOM (byte order mark)
this breaks uglifyjs and finding the cause of it took me half and hour
just remove it. thanks

**Comment by Mottie** [comment]
Sorry about that, my editor adds that when I try to save the file as UTF-8. Someday I'll switch completely over to using Sublime Text 2 where that isn't an issue.

I'll have this fixed in the next update, thanks!

**Comment by Mottie** [comment]
Fixed in version 2.3!
