### ISSUE TITLE
hiding text when panel comes into view

### ISSUE THREAD

**Issue by DizzyBHigh** [CSS-Tricks/MovingBoxes#95]
any ideas on how to have the text hidden using $('textholder').hide / show

textholder would be the id or class i have holding the text, i would like to have it hidden and then displayed on the currently active item then hidden again when it is not active

hope that makes sense and there is an easy way of doing this

thanks in advance

**Comment by Mottie** [comment]
Hi DizzyBHigh!

Maybe [this demo](http://jsfiddle.net/Mottie/r6yWC/2/) that dims non-current panels will give you an idea of how to do this. It only uses CSS to accomplish the dimming, so if you need, you can add come css3 animation to it as well.

**Comment by DizzyBHigh** [comment]
thanks got it working :)
