### ISSUE TITLE
When wrap:true the slider starts with a .cloned panel

### ISSUE THREAD

**Issue by beshur** [CSS-Tricks/MovingBoxes#97]
Though the `.cloned` is not counted as real.
Also when I click (or trigger click) on any of the arrows,  the last slide is displayed.

The `startPanel` option does not help with this.

Has anyone met this?

Demo http://jsfiddle.net/beshur/mNYxQ/
You can see that the 'kitty' slide (which is the last one) is appended in the first place, though when clicking 'next' the second slide is displayed.

Thanks for any help.

**Comment by Mottie** [comment]
Hi beshur!

Hmm, I think this is definitely a bug... I'll fix this as soon as I can (tomorrow).

**Comment by beshur** [comment]
Thank you for reply, Mottie!
That would be really great.

**Comment by beshur** [comment]
Fantastic!
Thank you so much!
